# How to generate to valid deploy_rsa.enc file ?
#
# Generate a dedicated SSH key :
# ssh-keygen -t rsa -b 4096 -C 'build@travis-ci.org' -f ./deploy_rsa
# 
# Encrypt the private key and add $encrypted_xxx_key and $encrypted_xxx_key to the env
# travis login --org
# travis encrypt-file deploy_rsa -p --add
# 
# Copy the public key onto the remote SSH server
# ssh-copy-id -i deploy_rsa.pub <ssh-user>@<deploy-host>
# 
# Remove the key from your computer
# rm -f deploy_rsa deploy_rsa.pub
# 
# Add the key to github
# git add deploy_rsa.enc
# 
addons:
  ssh_known_hosts: ssh.cluster011.hosting.ovh.net
  
before_script:
  - npm install -g gulp-cli
  - npm install

script: 
  - gulp build

# Unlock private key
before_deploy:
  - openssl aes-256-cbc -K $encrypted_01d8626a5554_key -iv $encrypted_01d8626a5554_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist/ loireatl-ds@ssh.cluster011.hosting.ovh.net:/home/loireatl-ds/
  on:
    branch: master