version: '3'
services:
  site:
    container_name: dsbuilder
    command: bash -c "npm set strict-ssl false && npm install && gulp serve"
    image: julienbayle/dsbuilder
    build: .
    volumes:
      - ./..:/app
      - ./cache/bundle:/usr/local/bundle
    ports:
      - ${PORT}:4000
